### ISSUE TITLE
AI girls using the latest version will drop FPS

### ISSUE THREAD

**Issue by ArcticFoxGame** [OrangeSpork/AdvIKPlugin#2] opened 2021-12-18 14:09 UTC
AI girls will drop about 20FPS after use，But this problem is not very serious in version 1.6.6。Can you check why?

**Comment by ArcticFoxGame** [comment] 2021-12-19 12:48
HoneySelect2 also has the same problem!

**Comment by OrangeSpork** [comment] 2021-12-19 22:03
I'm not seeing any performance differences between 1.6.6 and 1.6.7 and there's no supporting information here to help narrow down a specific issue.

At the very least, please post up an output log from an affected session. A scene card or some other description of where you are measuring a frame drop and the circumstances around it would help.

**Comment by ArcticFoxGame** [comment] 2021-12-20 05:07
![Use 1 6 7](https://user-images.githubusercontent.com/44396719/146714341-38d8c494-04d3-4a0e-bc1d-ff5f2a49c38e.png)
after loading 1.6.7
![Use 1 6 6](https://user-images.githubusercontent.com/44396719/146714396-f5213599-7d43-47eb-857a-a10f9fad53d1.png)
after loading 1.6.6
The log does not indicate any errors or warnings！
I found that this problem occurs when 1.6.7 is loaded, even if all the functions of the plug-in are turned off.
The same is true for turning off all functions of the plug-in and restarting the game.

**Comment by ArcticFoxGame** [comment] 2021-12-20 05:08
> I'm not seeing any performance differences between 1.6.6 and 1.6.7 and there's no supporting information here to help narrow down a specific issue.
> 
> At the very least, please post up an output log from an affected session. A scene card or some other description of where you are measuring a frame drop and the circumstances around it would help.

![Use 1 6 7](https://user-images.githubusercontent.com/44396719/146714341-38d8c494-04d3-4a0e-bc1d-ff5f2a49c38e.png)
【after loading 1.6.7】
![Use 1 6 6](https://user-images.githubusercontent.com/44396719/146714396-f5213599-7d43-47eb-857a-a10f9fad53d1.png)
【after loading 1.6.6】

The log does not indicate any errors or warnings！
I found that this problem occurs when 1.6.7 is loaded, even if all the functions of the plug-in are turned off.
The same is true for turning off all functions of the plug-in and restarting the game.

**Comment by OrangeSpork** [comment] 2021-12-20 07:18
An output log contains more than just the presence or absence of errors. Please post an output log. 

Also I need to know where IN THE GAME you are seeing/measuring the frame drop. Studio, main game, maker, all of the above? Is there a particular character affected. Does it reproduce on say the main menu with no characters showing? 

I can't fix an issue I can't reproduce, and neither I nor anyone else has been able to reproduce this, I'm going to need more information or there isn't anything I can do.

**Comment by ArcticFoxGame** [comment] 2021-12-20 09:57
> An output log contains more than just the presence or absence of errors. Please post an output log.
> 
> Also I need to know where IN THE GAME you are seeing/measuring the frame drop. Studio, main game, maker, all of the above? Is there a particular character affected. Does it reproduce on say the main menu with no characters showing?
> 
> I can't fix an issue I can't reproduce, and neither I nor anyone else has been able to reproduce this, I'm going to need more information or there isn't anything I can do.

[output_log.txt](https://github.com/OrangeSpork/AdvIKPlugin/files/7744315/output_log.txt)
This is the output log.I couldn't figure out the problem.
This problem of AI-Syoujo appears in the main game and character creation. The others have not had time to test.
This problem of HoneySelect2 is very serious in Maker, but it is not so serious in other places.
I used the default role of the game, other roles have also been tested, it is not a role problem.
I tested the main menu of HoneySelect2, the impact is very small, basically negligible.
I don't know why, but I will try to recompile and test with source code when I have time.

**Comment by OrangeSpork** [comment] 2021-12-21 01:58
Hmm, Maker eh? I tweaked a few things that might be relevant...try and see if this fixes the issue...
[AI_AdvIKPlugin.zip](https://github.com/OrangeSpork/AdvIKPlugin/files/7749027/AI_AdvIKPlugin.zip)
[HS2_AdvIKPlugin.zip](https://github.com/OrangeSpork/AdvIKPlugin/files/7749028/HS2_AdvIKPlugin.zip)

**Comment by ArcticFoxGame** [comment] 2021-12-21 05:33
> Hmm, Maker eh? I tweaked a few things that might be relevant...try and see if this fixes the issue... [AI_AdvIKPlugin.zip](https://github.com/OrangeSpork/AdvIKPlugin/files/7749027/AI_AdvIKPlugin.zip) [HS2_AdvIKPlugin.zip](https://github.com/OrangeSpork/AdvIKPlugin/files/7749028/HS2_AdvIKPlugin.zip)

I have tested it and the FPS of AI and HS2 has returned to normal.Thanks!

**Comment by OrangeSpork** [comment] 2021-12-21 06:23
Ah, odd that traversing an empty list was eating that much time...but good to fix anyway. Resolved in 1.6.8 build.

**Closed as completed by OrangeSpork** 2021-12-21 06:23 UTC

**Comment by ArcticFoxGame** [comment] 2021-12-21 08:02
> Ah, odd that traversing an empty list was eating that much time...but good to fix anyway. Resolved in 1.6.8 build.

I found that if the plug-in function is turned off in the plug-in settings, the same problem will occur.But as long as the plug-in function is turned on, there is no such problem。
This problem will only appear in the main game mode of AI, but it can basically be ignored, because the main game mode is basically not closed.
